name: Build

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        - run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Release with maven
        run: mvn -B release:prepare release:perform
