name: Sync

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build"]

jobs:
  sync:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'maven-scm') }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
      - name: remote add
        run: |
          git remote add cm https://akalfas-adobe-com:${{ secrets.CM_PAT }}@git.cloudmanager.adobe.com/cmteam/ak-rde-p100352-uk71048/
      - name: fetch gh
        run: |
          git fetch origin --quiet
      - name: push to cm
        run: |
          git push cm "refs/remotes/origin/main:refs/heads/main" --force
