name: Sync

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build"]

jobs:
  sync:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'maven-scm') }}
    steps:
      - uses: actions/checkout@v3
      - name: sync
        run: |
          git remote -v
          git remote add cm https://akalfas-adobe-com:${{ secrets.CM_PAT }}@git.cloudmanager.adobe.com/cmteam/ak-rde-p100352-uk71048/
          git fetch cm
          git checkout cm/main
          git merge main
          git push cm main
          
