name: Sync

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build"]

sync:
  runs-on: ubuntu-latest
  if: ${{ !contains(github.event.head_commit.message, 'maven-scm') }}
  steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_PAT }}
    - name: Sync
      run: |
        git remote add cm https://akalfas-adobe-com:${{ secrets.CM_PAT }}@git.cloudmanager.adobe.com/cmteam/ak-rde-p100352-uk71048/
        git pull cm main -r
        git push cm main
