name: Sync

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build"]

jobs:
  sync:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'maven-scm') }}
    steps:
      - uses: actions/checkout@v3
      - name: sync
        run: |
          git remote -v
